apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pumba-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu-server
    spec:
      containers:
      - name: server
        image: ubuntu:latest
        ports:
        - containerPort: 8080
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "apt-get update; apt-get install -y iperf net-tools iproute2; while true; do sleep 30; done;" ]