apiVersion: batch/v1
kind: Job
metadata:
  name: selenium
  labels:
    tugbot-kubernetes-events: ReplicaSet.SuccessfulCreate
spec:
  template:
    metadata:
      name: selenium
    spec:
      containers:
      - name: selenium-tests
        image: wayfactory/selenium-eads:latest
        command: [ "bash", "-c", "sudo /bin/bash /src/prepare-container.sh; xvfb-run python /src/example.py;" ]
      restartPolicy: Never
